version: "3.9"
services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '--path.procfs /host/proc --path.sysfs /host/sys --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/data
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/data'
      - '-alertmanager.url=http://alertmanager:9093'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
      - ./alertmanager/data:/data
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/data'
    links:
      - mailhog

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/data:/var/lib/grafana"

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

