global:
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'somkiat.p@gmail.com'
  smtp_require_tls: false

route:
  receiver: 'mailhog'

receivers:
  - name: 'mailhog'
    email_configs:
      - to: somkiat.p@gmail.com
        send_resolved: true

