version: '3.7'

services:
  api:
    image: nginx
    # docker-compose up -d api
    # docker-compose ps
  
  kong-database:
    image: postgres:12-alpine
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api2:
    image: somkiat/hello
    ports:
      - 8080:8000
  migrations:
    depends_on:
      - kong-database
    image: kong:latest
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap -v

  kong:
    depends_on:
      - kong-database
    image: kong
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl http2
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
    ports:
      - 80:8000
      - 443:8443 
      - 127.0.0.1:8001:8001
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://127.0.0.1:8001/status"]
      interval: 5s
      timeout: 2s
      retries: 15

  mongo:
    image: mongo
    restart: always
    container_name: konga_mongo
    volumes:
      - ./mongo_data:/data/db

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      DB_ADAPTER: mongo
      DB_HOST: mongo
    depends_on:
      - mongo
    ports:
      # - 127.0.0.1:1337:1337
      - 1337:1337   

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    restart: always
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
    ports: 
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: 
      - 5601:5601