version: "3.9"
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      # Enable JMX remote
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    networks:
     - demo_network
      
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
     - demo_network

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: --kafka.server=kafka:9092
    ports:
      - "9308:9308"
    environment:
      KAFKA_BROKERCONNECT: "kafka:2181"
    networks:
     - demo_network
  
  jmx-exporter:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556:5556"
    environment:
      SERVICE_PORT: 5556
    volumes:
      - ./jmxexporter.yml:/opt/jmx_exporter/config.yml

networks:
  demo_network:
    name: demo_network
    driver: bridge