version: "3.9"
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    networks:
     - demo_network
      
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
     - demo_network

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: --kafka.server=kafka:9092
    ports:
      - "9308:9308"
    environment:
      KAFKA_BROKERCONNECT: "kafka:2181"
    networks:
     - demo_network

networks:
  demo_network:
    name: demo_network
    driver: bridge