version: '3.9'
services:
  redis1:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis2:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis3:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster:
    tty: true
    image: redis:6
    command: redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-replicas 0